---
    - hosts: localhost
      connection: local
      become: yes
      become_user: ec2-user
      vars:
        ansible_python_interpreter: /usr/bin/python2   
      vars_files:
        - ../groupvars/var.yml
      
      tasks:

        # - name: add proxy to ec2-user
        #   lineinfile:
        #     dest: /home/ec2-user/.bashrc
        #     line: '{{ item }}'
        #   with_items:
        #     - 'export http_proxy="http://172.18.10.246:80"'
        #     - 'export https_proxy="http://172.18.10.246:80"'
        #     - 'export no_proxy="localhost, .cat.com, 169.254.169.254"'  
        #   tags: default
             
        # - name: add proxy to system environment file
        #   lineinfile:
        #     dest: /etc/environment
        #     line: '{{ item }}'
        #   with_items:
        #     - 'export http_proxy="http://172.18.10.246:80"'
        #     - 'export https_proxy="http://172.18.10.246:80"'
        #     - 'export no_proxy="localhost, .cat.com, 169.254.169.254"'
        #   become_user: root 
        #   tags: default

        - name: checking vsts exits or not
          stat:      
            path: /home/ec2-user/Agent01
          register: vsts_dir
          tags: default

        - name: download the vsts agent
          get_url:
            url:  https://vstsagentpackage.azureedge.net/agent/2.173.0/vsts-agent-linux-x64-2.173.0.tar.gz
            dest: /tmp/vsts-agent-linux-x64-2.173.0.tar.gz
            force: yes
          when: not vsts_dir.stat.exists
          tags: default 
        
        - name: create directory vsts agent
          file:
            path: /home/ec2-user/{{ item }}
            state: directory
          with_items:
            - Agent01
            - Agent02
          when: not vsts_dir.stat.exists
          tags: default      
        
        - name : unpack the downloaded vsts agent01
          unarchive:
            src: /tmp/vsts-agent-linux-x64-2.173.0.tar.gz
            dest: /home/ec2-user/Agent01
          when: not vsts_dir.stat.exists
          tags: default

        - name : unpack the downloaded vsts agent02
          unarchive:
            src: /tmp/vsts-agent-linux-x64-2.173.0.tar.gz
            dest: /home/ec2-user/Agent02
          when: not vsts_dir.stat.exists
          tags: default
           
        - name: check if java is installed
          shell: |
            source ~/.bashrc
            java -version
          register: java_result
          ignore_errors: True
          tags: default

        - name: sdkman installation script download
          get_url: 
            url: https://get.sdkman.io 
            dest: /home/ec2-user/run.sh
            mode: 0755
          when: java_result is failed
          tags: java11

        - name : run sdkman installation script
          shell: bash /home/ec2-user/run.sh  
          when: java_result is failed
          tags: java11

        - name: source sdk and Install the java 11.0.2-open
          shell: |
            source ~/.bashrc
            sdk install java 11.0.2-open
            sdk use java 11.0.2-open
          args:
            executable: /bin/bash
          when: java_result is failed
          tags: java11 
                 
        - name: download java8 rpm
          get_url:
             url: "{{ item.value.url }}"
             headers: "{{ item.value.args }}"
             force: yes
             dest: /tmp
          with_dict: "{{ java }}"
          when: java_result is failed
          tags: java8  
      
        - name: install package java8
          command: rpm -i /tmp/jdk-8u141-linux-x64.rpm
          args:
            warn: no
          when: java_result is failed
          become_user: root
          tags: java8 

        - name: check if maven is installed
          shell: |
            source ~/.bashrc
            mvn --version
          register: maven_result
          ignore_errors: True
          tags: default

        - name: download Maven
          get_url:
             url: "{{ item.value.url }}"
             force: yes
             dest: /tmp
          with_dict: "{{ maven }}" 
          when: maven_result is failed
          tags: default

        - name: unarchive Maven
          unarchive:
             src: /tmp/apache-maven-3.6.3-bin.tar.gz
             dest: /usr/local/
             mode: 0755
             owner: root
             group: root  
          when: maven_result is failed
          become_user: root
          tags: default

        - name: move maven bin to /usr/local
          command: mv /usr/local/apache-maven-3.6.3 /usr/local/apache-maven
          when: maven_result is failed
          become_user: root                  
          tags: default

        - name: create maven environment
          lineinfile:
            dest: /home/ec2-user/.bashrc
            line: '{{ item }}'
          with_items:
            - 'export M2_HOME=/usr/local/apache-maven'
            - 'export M2=$M2_HOME/bin'
            - 'export PATH=$M2:$PATH'
          tags: default
        
        - name: create m2 directory
          file: 
            path: /home/ec2-user/.m2
            state: directory
          tags: default

        - name: create mvn settings file
          file: 
            path: /home/ec2-user/.m2/settings.xml
            state: touch
          tags: default

        - name: sbt Installation
          shell: curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
          args:
            warn: no 
            executable: /bin/bash
          become_user: root
          tags: default

        - name: Install yum package
          yum:
           name:
             - curl-devel
             - expat-devel
             - gettext-devel
             - openssl-devel
             - zlib-devel
             - wget
             - gcc
             - cpan
             - unzip
             - zip
             - docker
             - python3
             - postgresql-server
             - sbt
          become_user: root
          tags: default
        
        - name: add proxy to docker
          lineinfile:
            dest: /etc/sysconfig/docker
            line: '{{ item }}'
          with_items:
            - 'HTTP_PROXY=http://172.18.10.246:80'
            - 'HTTPS_PROXY=http://proxy.cat.com:80/'
            - 'NO_PROXY="localhost, .cat.com, 169.254.169.254"'
          become_user: root
          tags: default
    
        - name: start Docker service
          service:
              name: docker
              state: started
              enabled: yes 
          become_user: root   
          tags: default

        - name: add user ec2-user to docker group
          user:
            name: ec2-user
            groups: docker
            append: yes
          become_user: root
          tags: default

        - name: install Docker Compose
          get_url:
             url:  "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64"
             dest: /usr/local/bin/docker-compose
             owner: root
             mode: 0755  
          become_user: root
          tags: default

        - name: check python version 
          command: python3 --version         
          register: python_result
          tags: default

        - name: create python virtual env directory 
          file:
            path: /home/ec2-user/python3
            state: directory  
          tags: default

        - name: install python virtual env
          shell: python3 -m pip install --user virtualenv
          args:
             executable: /bin/bash 
          tags: default         
  
        - name: install python virtual environment
          command:
            cmd: python3 -m venv /home/ec2-user/python3
          tags: default

        - name: nodejs and npm installation
          get_url:
               url: https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh
               dest: /home/ec2-user/install.sh
               mode: 0755   
          tags: default

        - name: run shell script
          shell: bash /home/ec2-user/install.sh
          args:
            executable: /bin/bash
          tags: default
       
        - name: nvm install 12.7.0
          shell: |
            source ~/.bashrc 
            nvm install 12.7.0 
          args:
            executable: /bin/bash
          tags: default

        - name: check npm and node version
          shell: |
            source ~/.bashrc
            npm -v && node -v 
          register: version_message
          ignore_errors: yes
          tags: default

        - debug:
            msg: "{{version_message}}"  
          tags: default

        - name: add  sbt environtment 
          lineinfile:
            dest:  /etc/environment
            line: '{{item}}'
          with_items:
            -  'export SBT_OPTS="-Dhttp.proxyHost=172.18.10.246 -Dhttp.proxyPort=80 -Dhttps.proxyHost=172.18.10.246 -Dhttps.proxyPort=80 -Xmx4096s"' 
          become_user: root        
          tags: java11

        - name: checking awscli 2 exits or not
          stat:      
            path: /opt/awscliv2
          register: awscli_cli
          tags: default

        - name: Download the aws cli
          get_url:
            url:  https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: /tmp/awscliv2.zip
            force: yes
          when: not awscli_cli.stat.exists
          tags: default

        - name: create directory aws cli temp agent
          file:
            path: /opt/awscliv2
            state: directory
          become_user: root
          tags: default  

        - name : unpack the downloaded aws cli
          unarchive:
            src: /tmp/awscliv2.zip
            dest: /opt/awscliv2
          when: not awscli_cli.stat.exists
          become_user: root
          tags: default

        - name: install aws cli 
          shell: /opt/awscliv2/aws/install
          become_user: root
          ignore_errors: True
          tags: default
          when: not awscli_cli.stat.exists

        - name: check aws cli version
          shell: aws --version
          register: awscli_version_message
          ignore_errors: yes
          tags: default

        - debug:
            msg: "{{awscli_version_message}}"  
          tags: default