---
- hosts: all
  user: localhost
  become: yes
  become_user: ubuntu
  vars_files:
    - ../groupvars/var.yaml

  tasks:
    - name: Add proxy to ec2-user 
      lineinfile: 
        dest: /home/ubuntu/.bashrc
        line: '{{ item }}'
      with_items:
              - 'export http_proxy="http://172.18.10.246:80"'
              - 'export https_proxy="http://172.18.10.246:80"'
              - 'export no_proxy="localhost, .cat.com, 169.254.169.254"'

    - name: Add proxy to ec2-user 
      lineinfile: 
        dest: /etc/environment
        line: '{{ item }}'
      with_items:
        - 'export http_proxy="http://172.18.10.246:80"'
        - 'export https_proxy="http://172.18.10.246:80"'
        - 'export no_proxy="localhost, .cat.com, 169.254.169.254"'

    - name: Check if java is installed
      command: java -version
      register: java_result
      ignore_errors: True

    - debug:
        msg: "Failed - Java is not installed"
      when: java_result is failed

    - debug:
        msg: "Success - Java is installed"
      when:  java_result is success

    - name: Download java8
      get_url: 
        url: "{{ item.value.url }}"
        headers: "{{ item.value.args }}"
        force: yes
        dest: /tmp
      with_dict: "{{ java8 }}"
      when: java_result is failed 

    - name: Install package java8
      yum:
        name: /tmp/jdk-8u141-linux-x64.rpm
        state: present
      when: java_result is failed

    - name: Download Maven
      get_url: 
        url: "{{ item.value.url }}"
        force: yes
        dest: /tmp
      with_dict: "{{ maven }}"
      
    - name: Unarchive Maven
      unarchive:
        src: /tmp/apache-maven-3.6.3-bin.tar.gz
        dest: /opt/
        mode: 0755
        owner: root
        group: root